import { i } from "@instantdb/react";

const _schema = i.schema({
  entities: {
    $users: i.entity({
      email: i.any().unique().indexed(),
    }),
    admins: i.entity({
      email: i.string().unique().indexed(),
      note: i.string().optional(),
      createdAt: i.number().indexed(),
      createdBy: i.string().optional(),
    }),
    rooms: i.entity({
      code: i.string().unique().indexed(),
      hostClientId: i.string().indexed(),
      hostUserId: i.string().optional().indexed(),
      hostEmail: i.string().optional(),
      hostName: i.string(),
      activePlayerId: i.string().optional().indexed(),
      status: i.string().indexed(),
      roundIndex: i.number().indexed(),
      roundCount: i.number(),
      submissionSeconds: i.number(),
      difficulty: i.string(),
      revealIndex: i.number(),
      scenarioTitle: i.string().optional(),
      scenarioText: i.string().optional(),
      immediateThreat: i.string().optional(),
      timePressure: i.string().optional(),
      category: i.string().optional(),
      bannedWords: i.json<string[]>().optional(),
      deadlineAt: i.number().optional().indexed(),
      hiddenFromHostHistory: i.boolean().optional().indexed(),
      finishedAt: i.number().optional().indexed(),
      archivedAt: i.number().optional().indexed(),
      cleanupReason: i.string().optional(),
      createdAt: i.number().indexed(),
      updatedAt: i.number().indexed(),
    }),
    players: i.entity({
      roomId: i.string().indexed(),
      clientId: i.string().indexed(),
      name: i.string(),
      seatIndex: i.number().indexed(),
      isHost: i.boolean(),
      connected: i.boolean(),
      ready: i.boolean(),
      score: i.number(),
      survivalCount: i.number(),
      deathCount: i.number(),
      joinedAt: i.number().indexed(),
      lastSeenAt: i.number(),
    }),
    submissions: i.entity({
      roomId: i.string().indexed(),
      roundIndex: i.number().indexed(),
      playerId: i.string().indexed(),
      clientId: i.string().indexed(),
      text: i.string(),
      submittedAt: i.number().indexed(),
      locked: i.boolean(),
    }),
    judgments: i.entity({
      roomId: i.string().indexed(),
      roundIndex: i.number().indexed(),
      playerId: i.string().indexed(),
      logicScore: i.number(),
      creativityScore: i.number(),
      feasibilityScore: i.number(),
      humorScore: i.number(),
      verdict: i.string(),
      survived: i.boolean(),
      pointsAwarded: i.number(),
      outcome: i.string(),
      judgeComment: i.string(),
      causeOfDeath: i.string().optional(),
      rawModelOutput: i.string().optional(),
      createdAt: i.number().indexed(),
    }),
  },
  links: {
    adminUsers: {
      forward: { on: "admins", has: "one", label: "user" },
      reverse: { on: "$users", has: "many", label: "adminRecords" },
    },
  },
});

export default _schema;
